# Generated by Django 5.0.7 on 2024-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_detail_guid', models.CharField(max_length=36)),
                ('alias', models.CharField(max_length=100)),
                ('parent_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('alias_formula', models.CharField(blank=True, max_length=100, null=True)),
                ('child_digits', models.IntegerField()),
                ('has_children', models.BooleanField(default=False)),
                ('is_item', models.BooleanField(default=True)),
                ('not_absolute_ratio', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_serial', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_code', models.CharField(blank=True, max_length=50, null=True)),
                ('old_code', models.CharField(blank=True, max_length=50, null=True)),
                ('model_no', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_group', models.CharField(blank=True, max_length=50, null=True)),
                ('technical_code', models.CharField(blank=True, max_length=50, null=True)),
                ('woocommerce_category_id', models.IntegerField(blank=True, null=True)),
                ('unit1_guid', models.CharField(max_length=36)),
                ('unit2_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('quantity1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_inventory', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woocommerce_product_id', models.IntegerField(blank=True, null=True)),
                ('woocommerce_variable_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
