# Generated by Django 5.0.7 on 2024-07-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('check_inventory', models.BooleanField(default=False)),
                ('default_depot_api', models.BooleanField(default=False)),
                ('pre_sell_invoice_check_inventory', models.BooleanField(default=False)),
                ('inventory_valuation', models.IntegerField()),
                ('item_gender', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('depot_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('user_groups', models.JSONField(blank=True, null=True)),
                ('item_groups', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepotIoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_description', models.TextField()),
                ('item_guid', models.CharField(max_length=36)),
                ('depot_io_guid', models.CharField(max_length=36)),
                ('reference_guid', models.CharField(max_length=36)),
                ('unit1', models.CharField(max_length=50)),
                ('unit1_guid', models.CharField(max_length=36)),
                ('unit1_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit2', models.CharField(blank=True, max_length=50, null=True)),
                ('unit2_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('unit2_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='DepotIo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_doc_no', models.CharField(max_length=50)),
                ('official', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('depot1_description', models.TextField()),
                ('depot1_code', models.CharField(max_length=50)),
                ('account_debit_guid', models.CharField(max_length=36)),
                ('account_credit_guid', models.CharField(max_length=36)),
                ('driver_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('driver_description', models.TextField(blank=True, null=True)),
                ('driver_code', models.CharField(blank=True, max_length=50, null=True)),
                ('depot2_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('depot2_description', models.TextField(blank=True, null=True)),
                ('depot2_code', models.CharField(blank=True, max_length=50, null=True)),
                ('depot1_guid', models.CharField(max_length=36)),
                ('expert_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('expert_description', models.TextField(blank=True, null=True)),
                ('expert_code', models.CharField(blank=True, max_length=50, null=True)),
                ('person_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_no', models.CharField(blank=True, max_length=50, null=True)),
                ('person_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('person_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('kind', models.IntegerField()),
                ('portage_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_list_guid', models.CharField(blank=True, max_length=36, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_status', models.CharField(max_length=10)),
                ('details', models.ManyToManyField(to='shop.depotiodetail')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='depots',
            field=models.ManyToManyField(through='shop.DepotIoDetail', to='shop.depot'),
        ),
    ]
